
apiVersion: v1
kind: List
metadata:
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: chaoskube
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  data:
    .dockerconfigjson: eyJhdXRocyI6eyJkb...FpXeHNhUT09In19fQ==
  kind: Secret
  metadata:
    namespace: chaoskube
    name: repocreds
  type: kubernetes.io/dockerconfigjson
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    namespace: chaoskube
    name: chaoskube
  imagePullSecrets:
  - name: repocreds
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: chaoskube
    namespace: chaoskube
    labels:
      app: chaoskube
  spec:
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: chaoskube
    template:
      metadata:
        labels:
          app: chaoskube
      spec:
        serviceAccountName: chaoskube
        containers:
        - name: chaoskube
          image: <your.local.repository>/chaoskube:v0.21.0
          args:
          # kill a pod every 10 minutes
          - --interval=1m
          # only target pods in the test environment
          - --labels=environment=test
          # only consider pods with this annotation
          - --annotations=chaos.alpha.kubernetes.io/enabled=true
          # exclude all DaemonSet pods
          - --kinds=!DaemonSet
          # exclude all pods in the kube-system namespace
          - --namespaces=!kube-system
          - --namespaces=test-project
          # don't kill anything on weekends
          - --excluded-weekdays=Sat,Sun
          # don't kill anything during the night or at lunchtime
          - --excluded-times-of-day=22:00-08:00,11:00-13:00
          # don't kill anything as a joke or on christmas eve
          - --excluded-days-of-year=Apr1,Dec24
          # let's make sure we all agree on what the above times mean
          - --timezone=UTC
          # exclude all pods that haven't been running for at least one hour
          - --minimum-age=1h
          # terminate pods for real: this disables dry-run mode which is on by default
          - --no-dry-run
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
  


- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: chaoskube
  rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: chaoskube
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: chaoskube
  subjects:
  - kind: ServiceAccount
    name: chaoskube
    namespace: chaoskube
